export type { DeckProps } from './components/Deck'
export { Deck } from './components/Deck'
export type { NotesProps } from './components/Notes'
export { Notes } from './components/Notes'
export type { SlideProps } from './components/Slide'
export { Slide } from './components/Slide'
export type { DeckContextValue } from './context'
export { useDeck } from './context'
